env:
  browser: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'react'
  - 'prettier'
  - 'prettier/react'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  describe: readonly
  it: readonly,
  beforeEach: readonly
  jest: readonly
  expect: readonly
  global:
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
